"""add_risk_score_table

Revision ID: 30bcb93243c2
Revises: 390b5956d930
Create Date: 2026-03-28 06:02:34.293717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30bcb93243c2'
down_revision: Union[str, None] = '390b5956d930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactionriskscore',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('is_confirmed_fraud', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionriskscore_risk_score'), 'transactionriskscore', ['risk_score'], unique=False)
    op.create_index(op.f('ix_transactionriskscore_transaction_id'), 'transactionriskscore', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactionriskscore_transaction_id'), table_name='transactionriskscore')
    op.drop_index(op.f('ix_transactionriskscore_risk_score'), table_name='transactionriskscore')
    op.drop_table('transactionriskscore')
    # ### end Alembic commands ###
