"""add_risk_score_model

Revision ID: 390b5956d930
Revises: 42e498177ef8
Create Date: 2026-03-27 17:57:55.125738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390b5956d930'
down_revision: Union[str, None] = '42e498177ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
          CREATE TYPE aireviewstatusenum AS ENUM (
            'PENDING',
            'FLAGGED',
            'CLEARED',
            'CONFIRMED_FRAUD'
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column(
        "transaction",
        sa.Column(
            "ai_review_status",
            sa.Enum(
                "PENDING",
                "FLAGGED",
                "CLEARED",
                "CONFIRMED_FRAUD",
                name="aireviewstatusenum",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "ai_review_status")

    op.execute("DROP TYPE aireviewstatusenum;")
    # ### end Alembic commands ###