"""add_next_of_kin_table

Revision ID: 4f2475bad8f9
Revises: 6ac97b6c3f41
Create Date: 2026-03-23 11:37:30.671091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f2475bad8f9'
down_revision: Union[str, None] = '6ac97b6c3f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nextofkin',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('relationship', sa.Enum('Spouse', 'Parent', 'Child', 'Sibling', 'Other', name='relationshiptypeenum'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('profile', 'title',
               existing_type=postgresql.ENUM('Mr', 'Mrs', 'Miss', name='salutations'),
               type_=sa.Enum('Mr', 'Mrs', 'Miss', name='salutationenum'),
               existing_nullable=False)
    op.alter_column('profile', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='genderschema'),
               type_=sa.Enum('Male', 'Female', 'Other', name='genderenum'),
               existing_nullable=False)
    op.alter_column('profile', 'marital_status',
               existing_type=postgresql.ENUM('Married', 'Divorced', 'Single', 'Widowed', name='maritalstatusschema'),
               type_=sa.Enum('Married', 'Divorced', 'Single', 'Widowed', name='maritalstatusenum'),
               existing_nullable=False)
    op.alter_column('profile', 'means_of_identification',
               existing_type=postgresql.ENUM('Passport', 'Drivers_License', 'National_ID', name='identificationtypeschema'),
               type_=sa.Enum('Passport', 'Drivers_License', 'National_ID', name='identificationtypeenum'),
               existing_nullable=False)
    op.alter_column('profile', 'employment_status',
               existing_type=postgresql.ENUM('Employed', 'Unemployed', 'Self_Employed', 'Student', 'Retired', name='employmentstatusschema'),
               type_=sa.Enum('Employed', 'Unemployed', 'Self_Employed', 'Student', 'Retired', name='employmentstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'employment_status',
               existing_type=sa.Enum('Employed', 'Unemployed', 'Self_Employed', 'Student', 'Retired', name='employmentstatusenum'),
               type_=postgresql.ENUM('Employed', 'Unemployed', 'Self_Employed', 'Student', 'Retired', name='employmentstatusschema'),
               existing_nullable=False)
    op.alter_column('profile', 'means_of_identification',
               existing_type=sa.Enum('Passport', 'Drivers_License', 'National_ID', name='identificationtypeenum'),
               type_=postgresql.ENUM('Passport', 'Drivers_License', 'National_ID', name='identificationtypeschema'),
               existing_nullable=False)
    op.alter_column('profile', 'marital_status',
               existing_type=sa.Enum('Married', 'Divorced', 'Single', 'Widowed', name='maritalstatusenum'),
               type_=postgresql.ENUM('Married', 'Divorced', 'Single', 'Widowed', name='maritalstatusschema'),
               existing_nullable=False)
    op.alter_column('profile', 'gender',
               existing_type=sa.Enum('Male', 'Female', 'Other', name='genderenum'),
               type_=postgresql.ENUM('Male', 'Female', 'Other', name='genderschema'),
               existing_nullable=False)
    op.alter_column('profile', 'title',
               existing_type=sa.Enum('Mr', 'Mrs', 'Miss', name='salutationenum'),
               type_=postgresql.ENUM('Mr', 'Mrs', 'Miss', name='salutationschema'),
               existing_nullable=False)
    op.drop_table('nextofkin')
    # ### end Alembic commands ###
